server:
  port: 8080
  tomcat:
    connection-timeout: 60000
    max-connections: 8192
    threads:
      max: 200
      min-spare: 10

spring:
  application:
    name: rent-house-management
  
  # 生产环境数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/rent_house?useUnicode=true&characterEncoding=utf8mb4&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&connectTimeout=30000&socketTimeout=60000
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: rent_house
    password: Qwesdx1245@
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 20
      minimum-idle: 5
      leak-detection-threshold: 60000
  
  # 生产环境JPA配置
  jpa:
    hibernate:
      ddl-auto: validate  # 生产环境使用validate，不自动修改表结构
    show-sql: false       # 生产环境关闭SQL日志
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Shanghai
        # 性能优化配置
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true
    open-in-view: false   # 关闭懒加载

# JWT配置 - 生产环境使用更安全的密钥
jwt:
  secret: rent-house-management-production-jwt-secret-key-2025-very-long-and-secure-key-for-production-use-only
  expiration: 86400000 # 24小时

# 生产环境日志配置
logging:
  level:
    root: INFO
    com.example.demo: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/rent-house-management.log
    max-size: 100MB
    max-history: 30

# Actuator配置 - 生产环境限制暴露的端点
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# Swagger配置 - 生产环境可选择关闭
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# 文件上传配置
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

# 应用信息
info:
  app:
    name: 房屋租赁管理系统
    version: 1.0.0
    description: 专业的房屋租赁管理解决方案
    build-time: 2025-08-08

# 数据初始化配置 - 生产环境关闭
data:
  init:
    enabled: false
