server:
  port: 8080
  tomcat:
    connection-timeout: 60000
    max-connections: 8192
    threads:
      max: 200
      min-spare: 10

spring:
  application:
    name: spring-boot-demo
  
  # 数据库配置 - MySQL
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot_demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&connectTimeout=30000&socketTimeout=60000
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        # 设置时区
        jdbc:
          time_zone: Asia/Shanghai
  
  # Redis配置 - 暂时禁用
  # data:
  #   redis:
  #     host: localhost
  #     port: 6379
  #     password: 
  #     database: 0
  #     timeout: 2000ms
  #     lettuce:
  #       pool:
  #         max-active: 8
  #         max-wait: -1ms
  #         max-idle: 8
  #         min-idle: 0

# JWT配置
jwt:
  secret: your-secret-key-here-make-it-long-and-secure
  expiration: 86400000 # 24小时

# 日志配置
logging:
  level:
    com.example.demo: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always

# Swagger配置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method 